//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discover_O_laptop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransaction
    {
        public string TransactionID { get; set; }
        public string LaptopID { get; set; }
        public int Quantity { get; set; }
    }
}
