//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discover_O_laptop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public string LaptopID { get; set; }
        public string LaptopBrandID { get; set; }
        public string LaptopName { get; set; }
        public string LaptopSize { get; set; }
        public string LaptopVGA { get; set; }
        public string LaptopRAM { get; set; }
        public int LaptopPrice { get; set; }
    }
}
